from enum import StrEnum

# Naming : [DOMAIN]_[ENTITY]_[PROBLEM]
class ErrorCode(StrEnum):
    # --- Generic ---
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

    # --- Registration & Login ---
    USERNAME_TAKEN = "USERNAME_TAKEN"
    EMAIL_TAKEN = "EMAIL_TAKEN"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"

    # --- Refresh Token ---
    REFRESH_TOKEN_MISSING = "REFRESH_TOKEN_MISSING"
    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID"
    REFRESH_TOKEN_PAYLOAD_INVALID = "REFRESH_TOKEN_PAYLOAD_INVALID"
    REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED"
    REFRESH_USER_NOT_FOUND = "REFRESH_USER_NOT_FOUND"

    # --- Access Token ---
    ACCESS_TOKEN_MISSING = "ACCESS_TOKEN_MISSING"
    ACCESS_TOKEN_INVALID = "ACCESS_TOKEN_INVALID"
    ACCESS_TOKEN_PAYLOAD_INVALID = "ACCESS_TOKEN_PAYLOAD_INVALID"
    ACCESS_USER_NOT_FOUND = "ACCESS_USER_NOT_FOUND"

    # --- Permissions ---
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"