from enum import StrEnum

# Naming : [DOMAIN]_[ENTITY]_[PROBLEM]
class ErrorCode(StrEnum):
    # --- Generic ---
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

    # --- Registration & Login ---
    USERNAME_TAKEN = "USERNAME_TAKEN"
    EMAIL_TAKEN = "EMAIL_TAKEN"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"

    # --- Refresh Token ---
    REFRESH_TOKEN_MISSING = "REFRESH_TOKEN_MISSING"
    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID"
    REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED"
    REFRESH_USER_NOT_FOUND = "REFRESH_USER_NOT_FOUND"

    # --- Access Token ---
    ACCESS_TOKEN_MISSING = "ACCESS_TOKEN_MISSING"
    ACCESS_TOKEN_INVALID = "ACCESS_TOKEN_INVALID"
    ACCESS_USER_NOT_FOUND = "ACCESS_USER_NOT_FOUND"

    # --- Reset Token ---
    RESET_TOKEN_INVALID = "RESET_TOKEN_INVALID"

    # --- Permissions ---
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"

    # --- Verification ---
    INVALID_VERIFICATION_ATTEMPT = "INVALID_VERIFICATION_ATTEMPT"

    # --- Rate Limits ---
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"

    # --- Category ---
    MASTER_CATEGORY_NOT_FOUND = "MASTER_CATEGORY_NOT_FOUND"
    SUB_CATEGORY_NOT_FOUND = "SUB_CATEGORY_NOT_FOUND"

    # --- Garment Type ---
    GARMENT_TYPE_NOT_FOUND = "GARMENT_TYPE_NOT_FOUND"

    # --- Gender ---
    GENDER_NOT_FOUND = "GENDER_NOT_FOUND"

    # --- Season ---
    SEASON_NOT_FOUND = "SEASON_NOT_FOUND"

    # --- Usage ---
    USAGE_NOT_FOUND = "USAGE_NOT_FOUND"

    # --- Color ---
    COLOR_NOT_FOUND = "COLOR_NOT_FOUND"

    # --- Garment ---
    GARMENT_NOT_FOUND = "GARMENT_NOT_FOUND"

    # --- Outfit ---
    OUTFIT_NOT_FOUND = "OUTFIT_NOT_FOUND"