""" description field null posibility

Revision ID: 24f1eb53b023
Revises: 4c6533f81888
Create Date: 2026-09-02 17:13:51.440604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f1eb53b023'
down_revision: Union[str, Sequence[str], None] = '4c6533f81888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories_master', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('categories_sub', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('garment_types', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('garments', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('genders', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('outfits', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('seasons', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('uses', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uses', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('seasons', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('outfits', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('genders', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('garments', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('garment_types', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('categories_sub', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('categories_master', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
