from .identity_repo_interface import UserIdentityRepositoryInterface
from .user_repo_interface import UserRepositoryInterface
from .role_repo_interface import RoleRepositoryInterface
from .user_role_repo_interface import UserRoleRepositoryInterface
from .refresh_token_repo_interface import RefreshTokenRepositoryInterface
from .category_master_repo_interface import CategoryMasterRepositoryInterface
from .generic_repo_interface import GenericRepositoryInterface